# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:title
relative_permalinks: true

# Dependencies
markdown:         kramdown
kramdown:
    input: GFM
#highlighter:      pygments

# Setup
title:               erikwb.net
tagline:             'Whatever escapes'
description:         'Just some of my ramblings.'
url:                  http://erikwb.net
baseurl:             ''
paginate:            5
# safe:                false

# About/contact
author:
  name:              Erik Wessel-Berg
  url:               https://twitter.com/erikwb
  email:             erik@wez.no

# Custom vars
version:             1.0.0
